version: "2"
services:
  ilibrarian: # Should be exact same name as "id" field in config.json
    container_name: ilibrarian # Should be exact same name as "id" field in config.json
    image: cgrima/i-librarian # Try to avoid "latest" tag. As it may break configs in the future.
    privileged: true
    restart: unless-stopped # Do not change this
    volumes:
      - /home/irobot/runtipi/app-data/ilibrarian/data:/app/data # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network # That should not be changed
